<?php
echo "<?php\n";
echo "/** Generated by ez-translations-helper on ". date('Y-m-d') ." at ". date('H:i:s') ." */\n\n";

echo "return array(\n";
$idContext = 0;
foreach ($results['contexts'] as $ctxName => $data) {
    $idContext++;
    echo "\n    // Context: $ctxName\n";
    $idTr = 0;
    foreach ($data['messages'] as $idx => $msg) {
        $idTr++;
        echo "    '". addslashes($msg['source']) ."'\t =>\t '". addslashes($msg['translation']) ."'". (($idContext >= count($results['contexts']) && $idTr >= count($data['messages'])) ? '' : ',') ."\n";
    }
}
echo ");\n";