<?php
echo "# Generated by ez-translations-helper on ". date('Y-m-d') ." at ". date('H:i:s') ."\n\n";

foreach ($results['contexts'] as $ctxName => $data) {
    echo "\n# Context: $ctxName\n";
    foreach ($data['messages'] as $idx => $msg) {
        echo "'". addslashes($msg['source']) ."': ". (empty($msg['translation']) ? "~" : $msg['translation']) ."\n";
    }
}
echo "\n";